version: "3.6"

services:

  game:
    image: vaynbaum/prj:game
    restart: always
    networks:
      - microservices
    ports:
      - 3000:3000

  post:
    image: vaynbaum/prj:post
    restart: always
    networks:
      - microservices
    ports:
      - 3001:3001

  similarity:
    image: vaynbaum/prj:similarity
    restart: always
    networks:
      - microservices
    ports:
      - 3002:3002
  
  gateway:
    image: vaynbaum/prj:gateway
    restart: always
    networks:
      - microservices
    ports:
      - 3003:3003

  frontend:
    image: vaynbaum/prj:frontend
    restart: always
    networks:
      - microservices
    ports:
      - 3004:3004
networks:
    microservices:
